name: Integration Tests Main

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
  run-integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "back-end/docker-compose-ci-test.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "back-end/docker-compose-ci-test.yml" down

  release-package:

    steps:

    - name: Checkout
        uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.9.3

    - name: compile to export
      run: |
        export DB_PASSWORD=default_mysql_pass
        cd back-end
        mvn clean install -DskipTests
        
    - name: Rename the artifact
        run: cp back-end/target/user-address-crud.jar user-address-crud-${{ github.sha }}.jar

    - name: Save the artifact
      uses: actions/upload-artifact@master
      with:
        name: user-address-crud-back-end
        path: user-address-crud-${{ github.sha }}.jar

  